/* This file is autogenerated by generate-buildinfo.sh */

#ifndef _EXAHYPE_BUILD_INFO_H_
#define _EXAHYPE_BUILD_INFO_H_

#define EXAHYPE_BUILDINFO_AVAILABLE
#define EXAHYPE_BUILD_DATE          "Fri Feb 3 11:03:02 GMT 2017"
#define EXAHYPE_BUILD_HOST          "localhost.localdomain"

/* Strings passed by the Makefile */
#define EXAHYPE_BUILD_INFO \
    "COMPILER = GNU\n" \
    "MODE = Asserts\n" \
    "SHAREDMEM = TBB\n" \
    "DISTRIBUTEDMEM = MPI\n" \
    "------\n" \
    "ARCHITECTURE = CPU\n" \
    "CC = /usr/lib64/mpi/gcc/openmpi/bin/mpiCC\n" \
    "BOUNDARYCONDITIONS = None\n" \
    "------\n" \
    "EXAHYPE_PATH = /home/tobias/git/ExaHyPE-Engine/./ExaHyPE\n" \
    "PROJECT_PATH = /home/tobias/git/ExaHyPE-Engine/./ApplicationExamples/EulerFlow\n" \
    "PEANO_KERNEL_PEANO_PATH = /home/tobias/git/ExaHyPE-Engine/./Peano/peano\n" \
    "PEANO_KERNEL_TARCH_PATH = /home/tobias/git/ExaHyPE-Engine/./Peano/tarch\n" \
    ""


/*
 * ExaHyPE Git Repository information extraction
 */

/* Information collected with git version 2.11.0 */
#define EXAHYPE_GIT_INFO "master  5bfb0ac5 Fri Feb 3 10:50:04 2017"

/*
 * Peano Subversion Repository information extraction
 */

/* Information collected with svn, version 1.9.5 (r1770682) */
#define PEANO_SVN_INFO "Rev 2470, 2017-01-14T13:46:39.857187Z"

#endif /* EXAHYPE_BUILD_INFO_H */
